using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System.Text.RegularExpressions;
using Testify.Shared.DTOs.Meetings;

namespace Testify.Services
{
    public class MeetingSummaryPdfDocument
    {
        private readonly MeetingSummaryResponse _summary;

        // Accent color matching Testify brand (#E85D3F)
        private static readonly string AccentColor = "#E85D3F";

        public MeetingSummaryPdfDocument(MeetingSummaryResponse summary)
        {
            _summary = summary;
        }

        public byte[] GeneratePdf()
        {
            QuestPDF.Settings.License = LicenseType.Community;

            return Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(2, Unit.Centimetre);
                    page.DefaultTextStyle(x => x.FontSize(10).FontFamily("Arial"));

                    // ── Header ──────────────────────────────────────────
                    page.Header().Column(header =>
                    {
                        header.Item().Row(row =>
                        {
                            row.RelativeItem().Column(col =>
                            {
                                col.Item().Text("MEETING MINUTES")
                                    .FontSize(8).Bold().FontColor(Colors.Grey.Medium)
                                    .LetterSpacing(0.1f);
                                col.Item().PaddingTop(4).Text(_summary.Title)
                                    .FontSize(18).Bold().FontColor(Colors.Grey.Darken4);
                                col.Item().Text(_summary.ProjectName)
                                    .FontSize(10).FontColor(Colors.Grey.Medium);
                            });
                            row.ConstantItem(100).AlignRight().Column(col =>
                            {
                                col.Item().Text("Tạo lúc").FontSize(8).FontColor(Colors.Grey.Medium);
                                col.Item().Text(_summary.GeneratedAt?.ToString("dd/MM/yyyy HH:mm") ?? "-")
                                    .FontSize(8).Bold();
                            });
                        });
                        header.Item().PaddingTop(10).BorderBottom(2).BorderColor(AccentColor);
                    });

                    // ── Content ─────────────────────────────────────────
                    page.Content().PaddingTop(16).Column(content =>
                    {
                        // Info row
                        content.Item().PaddingBottom(12).Row(row =>
                        {
                            row.RelativeItem().Column(col =>
                            {
                                col.Item().Text("BẮT ĐẦU").FontSize(7).Bold().FontColor(Colors.Grey.Medium);
                                col.Item().Text(_summary.StartedAt?.ToString("dd/MM/yyyy HH:mm") ?? "-").FontSize(9).Bold();
                            });
                            row.RelativeItem().Column(col =>
                            {
                                col.Item().Text("KẾT THÚC").FontSize(7).Bold().FontColor(Colors.Grey.Medium);
                                col.Item().Text(_summary.EndedAt?.ToString("dd/MM/yyyy HH:mm") ?? "-").FontSize(9).Bold();
                            });
                            row.RelativeItem().Column(col =>
                            {
                                col.Item().Text("THAM DỰ").FontSize(7).Bold().FontColor(Colors.Grey.Medium);
                                col.Item().Text($"{_summary.AttendedCount} / {_summary.ParticipantCount} người").FontSize(9).Bold();
                            });
                        });
                        content.Item().BorderBottom(1).BorderColor(Colors.Grey.Lighten2).PaddingBottom(0);
                        content.Item().PaddingTop(14).Column(body => RenderMarkdown(body, _summary.Summary ?? ""));
                    });

                    // ── Footer ──────────────────────────────────────────
                    page.Footer().PaddingTop(8).BorderTop(1).BorderColor(Colors.Grey.Lighten3)
                        .Row(row =>
                        {
                            row.RelativeItem().AlignLeft()
                                .Text("Generated by Testify AI").FontSize(8).FontColor(Colors.Grey.Medium);
                            row.RelativeItem().AlignRight().Text(text =>
                            {
                                text.Span("Trang ").FontSize(8).FontColor(Colors.Grey.Medium);
                                text.CurrentPageNumber().FontSize(8).FontColor(Colors.Grey.Medium);
                                text.Span(" / ").FontSize(8).FontColor(Colors.Grey.Medium);
                                text.TotalPages().FontSize(8).FontColor(Colors.Grey.Medium);
                            });
                        });
                });
            }).GeneratePdf();
        }

        // ─────────────────────────────────────────────────────────────────
        // Markdown → QuestPDF renderer
        // Supports: ## h2, ### h3, **bold**, *italic*, - bullet, --- divider, plain text
        // ─────────────────────────────────────────────────────────────────
        private static void RenderMarkdown(ColumnDescriptor col, string markdown)
        {
            if (string.IsNullOrWhiteSpace(markdown)) return;

            var lines = markdown.Replace("\r\n", "\n").Split('\n');

            foreach (var raw in lines)
            {
                var line = raw.TrimEnd();

                // ── Horizontal rule
                if (line == "---" || line == "***" || line == "___")
                {
                    col.Item().PaddingVertical(6).BorderBottom(1).BorderColor(Colors.Grey.Lighten2);
                    continue;
                }

                // ── H2  ## Heading
                if (line.StartsWith("## "))
                {
                    var text = line[3..].Trim();
                    col.Item().PaddingTop(10).PaddingBottom(2).Column(c =>
                    {
                        c.Item().Text(text.ToUpper())
                            .FontSize(11).Bold().FontColor(AccentColor).LetterSpacing(0.05f);
                        c.Item().BorderBottom(1).BorderColor(AccentColor);
                    });
                    continue;
                }

                // ── H3  ### Heading
                if (line.StartsWith("### "))
                {
                    var text = line[4..].Trim();
                    col.Item().PaddingTop(8).PaddingBottom(2).Text(text)
                        .FontSize(10).Bold().FontColor(Colors.Grey.Darken3);
                    continue;
                }

                // ── Bullet  - item  or  * item
                if (line.StartsWith("- ") || line.StartsWith("* "))
                {
                    var text = line[2..].Trim();
                    col.Item().PaddingLeft(12).PaddingBottom(2).Row(r =>
                    {
                        r.ConstantItem(10).PaddingTop(4).Text("•").FontSize(8).FontColor(AccentColor);
                        r.RelativeItem().Text(t => RenderInline(t, text));
                    });
                    continue;
                }

                // ── Empty line
                if (string.IsNullOrWhiteSpace(line))
                {
                    col.Item().PaddingBottom(3);
                    continue;
                }

                // ── Normal paragraph
                col.Item().PaddingBottom(3).Text(t => RenderInline(t, line));
            }
        }

        // Render inline markdown (**bold**, *italic*, [Chat]/[timestamp] markers)
        private static void RenderInline(TextDescriptor t, string text)
        {
            // Remove emoji chars that may cause font issues, keep text
            text = Regex.Replace(text, @"[🎙💬]", "");

            var remaining = text;
            while (remaining.Length > 0)
            {
                // **bold**
                var boldStart = remaining.IndexOf("**", StringComparison.Ordinal);
                if (boldStart >= 0)
                {
                    var boldEnd = remaining.IndexOf("**", boldStart + 2, StringComparison.Ordinal);
                    if (boldEnd >= 0)
                    {
                        if (boldStart > 0)
                            t.Span(remaining[..boldStart]).FontSize(10).LineHeight(1.5f);
                        t.Span(remaining[(boldStart + 2)..boldEnd]).Bold().FontSize(10).LineHeight(1.5f);
                        remaining = remaining[(boldEnd + 2)..];
                        continue;
                    }
                }

                // *italic*
                var itStart = remaining.IndexOf('*');
                if (itStart >= 0)
                {
                    var itEnd = remaining.IndexOf('*', itStart + 1);
                    if (itEnd >= 0)
                    {
                        if (itStart > 0)
                            t.Span(remaining[..itStart]).FontSize(10).LineHeight(1.5f);
                        t.Span(remaining[(itStart + 1)..itEnd]).Italic().FontSize(10).LineHeight(1.5f);
                        remaining = remaining[(itEnd + 1)..];
                        continue;
                    }
                }

                // Plain remainder
                t.Span(remaining).FontSize(10).LineHeight(1.5f);
                break;
            }
        }
    }
}
